### ISSUE TITLE
No module named 'bark.clonevoice'

### ISSUE THREAD

**Issue by KevinWang676** [C0untFloyd/bark-gui#1]
No module named 'bark.clonevoice'. I wonder how I can fix it. Thanks!

![image](https://user-images.githubusercontent.com/126712357/234430417-18330c3c-bb7b-4083-8466-ee0ca79fa777.png)

**Comment by C0untFloyd** [comment]
This was fixed by an update yesterday. Please update your version by using 'git pull'.

**Comment by KevinWang676** [comment]
I'm using Colab to run webui.py and the error is not fixed in my case. Could you help me check it?

![image](https://user-images.githubusercontent.com/126712357/234616633-9218203c-c0a2-4c7c-9d7e-ee49e0bfd364.png)

**Comment by C0untFloyd** [comment]
I never created a colab myself, so I doubt I would be of much help. But already your first line doesn't look right because it's the URL of the Suno GIT. It should probably read like [https://github.com/C0untFloyd/bark-gui.git](https://github.com/C0untFloyd/bark-gui.git). I also don't know if it's possible to run the Gradio UI on a Colab?!? I especially created this to not have to mess around with colabs and notebooks :wink:

**Comment by KevinWang676** [comment]
Haha, I see. Thank you!

**Comment by AIhasArrived** [comment]
@KevinWang676 
 I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
