### ISSUE TITLE
No module named 'build.lib'

### ISSUE THREAD

**Issue by KevinWang676** [C0untFloyd/bark-gui#17]
Hi, your recent update was amazing! It fixed the noise problem when using short prompts. However, when I'm on Colab, there is no module named 'build.lib'. So I replaced "from build.lib.bark.api import save_as_prompt" in webui.py with "from bark.api import save_as_prompt" and it worked out fine. I wonder if there is some specific reason why you used 'build.lib'. Also, will the above change of code cause any other problems? Thanks! It's really a great work.

**Comment by C0untFloyd** [comment]
` I wonder if there is some specific reason why you used 'build.lib`

Hey, I think you found a bug. I believe it was automatically imported by Visual Studio that way but the correct one is bark.api. It shouldn't cause any problems to you, because you're importing the correct one. Thanks for the heads up, fixing it now!
