### ISSUE TITLE
3 possible improvements

### ISSUE THREAD

**Issue by LuchunPen** [C0untFloyd/bark-gui#3]
Hi there ! Great work, I really like it, but I have 3 question for possible improvements, like in StableDiffusion by Automatic1111.

1. Local models storage. Now all models (OS windows) are downloading to Users/.cache folder. It will be great to change it to local in repository folder. For example bark/models
2. Add run vram options -medram, -lowram
3. Local cuda support without cuda install

**Comment by C0untFloyd** [comment]
1. Done with latest commits
2. This can always be done with the existing arguments: -forcecpu if you have not enough vram, -smallmodels -offloadcpu if you have less than 10 Gb and not specifying any of these is using big models
3. To use CUDA you need to install it, there's no way around this. I saw you mention somewhere else that Stable Diffusion works without a local install. This is not true, it will be installed automatically when using it for the first time. You probably forgot about it.

**Comment by LuchunPen** [comment]
About p3. 
Maybe yes, but it installed in local project folder in /env/ with all sitepackages. When I tried another one (GPT like project), It required to install CUDA plugin again.  It looks something like this "StableDiffusion_automatic1111\venv\Lib\site-packages\torch\lib\CUDA_FILES"

**Comment by AIhasArrived** [comment]
@LuchunPen 
 I have spent 3 entire weeks trying to find a way to clone correclty voices and I still did not get good results, I am so tired of it. I am contacting you because I saw you had old comments under old issues, you haev probably found better ways since then? Could you save me from my misery and direct me towards a method, a repo, a tutorial or anything that helps get to the point where I can actually clone a voice thats looks similar to the cloned voice please?  Help my soul lol. Really.
