### ISSUE TITLE
Where is the 1 click installer?

### ISSUE THREAD

**Issue by Magenta-6** [C0untFloyd/bark-gui#32]
I appreciate you making this available as it is an awesome application.
However I'm unsure where to find the 1 click installer for windows.

Also is there a preferred location where this should go, so that it gets linked to CUDA etc.  
                ie C:\UsersABC\Bark

or if I want to link it to oobabooga would it be better in that path?

Thanks and best regards

**Comment by C0untFloyd** [comment]
It's right here in the releases:
[https://github.com/C0untFloyd/bark-gui/releases/download/v07.1/bark_win_0.7.1.zip](https://github.com/C0untFloyd/bark-gui/releases/download/v07.1/bark_win_0.7.1.zip)

Usually the path or location doesn't matter, it probably shouldn't be that long because of windows name limits. Unfortunately I don't know about linking to oobabooga, Bark will create its own environment if that matters?

**Comment by Magenta-6** [comment]
Thanks @C0untFloyd  
I have Bark installed in about 3 places and none of them work properly, so I want to do a clean setup. 
I actually did look in the installer path but couldn't find the "releases"  branch there.  
https://github.com/C0untFloyd/bark-gui/tree/main/installer
Suggest a hyperlink in the readme.
Cheers for your prompt reply.
@Magenta-6

**Comment by Magenta-6** [comment]
PS: Installed just beautifully!
