### ISSUE TITLE
Training a language

### ISSUE THREAD

**Issue by MaxLanc** [C0untFloyd/bark-gui#44]
Hello and thanks for your hard work!

I've been messing around with bark and its pretty rad.
However I wonder how could I be able to train in the spanish language as a tokenizer model for the voice cloning mode?

So far the prepare data set tab has errored out and there doesn't seem to be any guide to train in this repo.

Is there any guide I can follow or what would be the steps to train a new tokenizer? I already have a bunch of spanish books ready to dl as plain text

Related error trace

```
To create a public link, set `share=True` in `launch()`.
Traceback (most recent call last):
  File "D:\Animax\vclone\bark_win\installer_files\env\lib\site-packages\gradio\routes.py", line 437, in run_predict
    output = await app.get_blocks().process_api(
  File "D:\Animax\vclone\bark_win\installer_files\env\lib\site-packages\gradio\blocks.py", line 1352, in process_api
    result = await self.call_function(
  File "D:\Animax\vclone\bark_win\installer_files\env\lib\site-packages\gradio\blocks.py", line 1077, in call_function
    prediction = await anyio.to_thread.run_sync(
  File "D:\Animax\vclone\bark_win\installer_files\env\lib\site-packages\anyio\to_thread.py", line 33, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(
  File "D:\Animax\vclone\bark_win\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 877, in run_sync_in_worker_thread
    return await future
  File "D:\Animax\vclone\bark_win\installer_files\env\lib\site-packages\anyio\_backends\_asyncio.py", line 807, in run
    result = context.run(func, *args)
  File "D:\Animax\vclone\bark_win\installer_files\env\lib\site-packages\gradio\helpers.py", line 602, in tracked_fn
    response = fn(*args)
  File "D:\Animax\vclone\bark_win\bark-gui\webui.py", line 192, in training_prepare
    prepare_semantics_from_text()
TypeError: prepare_semantics_from_text() missing 1 required positional argument: 'num_generations'
```

**Comment by C0untFloyd** [comment]
Yes, training right now seems to be broken and is in a very rough state. But I was able to train the german tokenizer with the Mylo Repo starting here [https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer](https://github.com/gitmylo/bark-voice-cloning-HuBERT-quantizer)
At the end of the page is a short section about training which links to another repo to prepare the training dataset.
From the top of my head, just a quick overview how it works:

1. You need to have about 6-7 input text sources (your spanish books). They need to be in raw text format, no fancy epub, pdf or something like that
2. These need to be feed to the standard bark engine, to generate audio (semantics) and text tokens.
3. You end up with a huge list of .wav files and the corresponding text.
4. These pairs are then fed into Hubert and trained for a number of epochs you decide. After each epoch you end up with the current tokenizer model and if you think it's doing good enough, stop training.

Using this tokenizer you can then clone spanish voices without having gibberish or english accent.

Hope this helps. I'm leaving this issue open because the bug still needs to be fixed in my repo.

**Comment by MaxLanc** [comment]
Thanks for the answer, already generating semantics from the texts.

A small question how many semantic files you think are good enough? Cuz I check the create_data and the semantic runs on a while 1.

**Comment by C0untFloyd** [comment]
My dataset for training is available [here](https://huggingface.co/CountFloyd) and the ones from Mylo are [here](https://huggingface.co/datasets/GitMylo/bark-semantic-training)
I just had a look, I've used about 3082 .npy files for training and the results were pretty good at 14 epochs.

**Comment by MaxLanc** [comment]
So... I trained a spanish tokenizer, how do I get bark gui to detect it and use it?

**Comment by C0untFloyd** [comment]
It's currently more or less hardcoded for the 3 existing ones so far. Best would be you just make it available (hugging face?) and I will of course include it in Bark. Also notify Mylo, he is collecting the links to custom tokenizers.

**Comment by MaxLanc** [comment]
Got it, for the time being I changed the name of the spanish tokenizer to the english one for testing lol, seems to work quite good

Already uploaded to Hugging btw
HF: Lancer1408/bark-es-tokenizer

**Comment by C0untFloyd** [comment]
🤦‍♂️
I completely forgot about the renaming possibility 😆 
In the meantime I added your tokenizer, no need to rename it anymore. Also, if you like to train some more, it might even work using the GUI now...

**Comment by yoesak** [comment]
Can you inform me how to add new language in bark instead of renaming the tokenizer file to en?

**Comment by C0untFloyd** [comment]
> Can you inform me how to add new language in bark instead of renaming the tokenizer file to en?

It's been quite a while but I believe it's enough to add it to this list:
https://github.com/C0untFloyd/bark-gui/blob/7c85e68d230d282cf0a9ba4ac7f0ef611329f60d/webui.py#L263

**Comment by yoesak** [comment]
Hi Thanks for your guidance, I succeeded to train my voice using the new language (Indonesian), 
but when I use it to generate the speak, bark result only silence sound, 

Since Bark doesn't support Indonesian language, how do I use the custom tokenizer from HuBert (from mylo) in the generation speak process?

In the MyLo's samples, he uses english, poland, german, and spanish, since all those languages supported by the bark naturally, and how to add to the bark itself?

**Comment by C0untFloyd** [comment]
That's something you need to ask the creators of bark https://github.com/suno-ai/bark
If it's not supported by the basic model you probably won't succeed to train it.
