### ISSUE TITLE
Not work very well with short prompts

### ISSUE THREAD

**Issue by KevinWang676** [C0untFloyd/bark-gui#8]
Hi there, I found that this repo doesn't work very well with short prompts in two or three words like "hello there". I wonder if this is related to some parameters you've set. Thanks! It's still an amazing fork of Bark!

**Comment by C0untFloyd** [comment]
Thanks, I also like your HF Page with Bark & YourTTS side-by-side 😄 
I believe Bark in general has a problem with short sentences, because it's then difficult to predict a sequence for things like intonation etc. I don't think there is something wrong with the parameters. Did you compare it with the original by Suno?
Also please try if this got better with the latest update, the v2 prompts should be more stable.

**Comment by KevinWang676** [comment]
Hi, I've tried v2 prompts with your repo, which still have some noise when the text is very short. Also, I think you need to comment out these two lines in the webui.py since it will cause extra "/" in prompts.
![image](https://user-images.githubusercontent.com/126712357/235818888-83f297c0-2cc1-47d0-a3e6-46c7814ed0fc.png)
![image](https://user-images.githubusercontent.com/126712357/235819108-33ad4cba-cae2-40c8-857f-6ad114fb4aaf.png)

By the way, I wonder why we need to first convert the text to ssml. Will it help the voice generation part? Thanks!

**Comment by C0untFloyd** [comment]
You are right about the "/" bug, this prevented the old voices from working. I'm doing it differently now...

> By the way, I wonder why we need to first convert the text to ssml. Will it help the voice generation part? Thanks!

You don't need to to use the ssml stuff. You can still just type anything into the input as before. The advantage of using SSML is that you can specify fixed voices for sentences, which you couldn't do previously.
